version: "3.9"

services:
  app:
    build: ./django_project
    container_name: django_project_container
    volumes:
      - static_files:/usr/src/static
      - ~/code_folder/home/django/to_test_rpc/django_project/app/migrations:/usr/src/app/migrations
    expose:
      - 8000
    depends_on:
      - postgres_db
    environment:
      - GUNICORN_PORT=8000

  app_second_instance:
    build: ./django_project_instance2
    container_name: django_project_container_instance2
    expose:
      - 8001
    depends_on:
      - postgres_db
    environment:
      - GUNICORN_PORT=8001

  app_third_instance:
    build: ./django_project_instance3
    container_name: django_project_container_instance3
    expose:
      - 8002
    depends_on:
      - postgres_db
    environment:
      - GUNICORN_PORT=8002

  app_fourth_instance:
    build: ./django_project_instance4
    container_name: django_project_container_instance4
    expose:
      - 8003
    depends_on:
      - postgres_db
    environment:
      - GUNICORN_PORT=8003

  postgres_db:
    image: postgres:14
    container_name: postgres_db_container
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=some_bd_name
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  redis_cache:
    image: redis
    container_name: redis_cache_container
    volumes:
      - redis_cache_data:/data

  nginx:
    build: ./nginx
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - static_files:/usr/src/static
    depends_on:
      - app

volumes:
  postgres_db_data:
  redis_cache_data:
  static_files:
